#include includes\spell_routines.inc
#turbo

Sub Main(string Search)
    /declare testIniFileName  string outer "Test.ini"
    /declare mezzRadius              int    outer 40
    /echo "DoMezz npc" ${SpawnCount[npc radius ${mezzRadius}]}
    /echo "DoMezz targetable" ${SpawnCount[targetable radius ${mezzRadius}]}
    /echo "DoMezz playerstate 4" ${SpawnCount[playerstate 4 radius ${mezzRadius}]}
    /echo "DoMEzz npc los" ${SpawnCount[npc los radius ${mezzRadius}]}
    /echo "Target level" ${Target.Level}
   
/return 

